### ISSUE TITLE
White screen with question mark when opening a game

### ISSUE THREAD

**Issue by StatueMarki** [TurboWarp/packager#823] opened 2024-02-16 07:39 UTC
Whenever I package a project and open the game, it just shows a white screen with a question mark. When I view the game in the preview though, it runs fine

**Comment by GarboMuffin** [comment] 2024-03-25 17:28
probably a duplicate of https://github.com/TurboWarp/packager/issues/838#issuecomment-2018529634

**Closed by GarboMuffin** 2024-03-25 17:28 UTC

**Comment by GarboMuffin** [comment] 2024-03-25 22:27
you didnt give us many details to work with but it probably works now
