### ISSUE TITLE
CLOSED

### ISSUE THREAD

**Issue by Pfoxj** [TurboWarp/packager#871] opened 2024-06-26 14:57 UTC
CLOSED

**Comment by GarboMuffin** [comment] 2024-06-27 02:28
duplicate of #2

**Closed by GarboMuffin** 2024-06-27 02:28 UTC

**Comment by Pfoxj** [comment] 2024-06-28 15:01
> duplicate of #2

Yeah I Know, I Wanted This To Get Closed, I Didn't Know About #2 When I made this issue
