### ISSUE TITLE
TurboWarp on android

### ISSUE THREAD

**Issue by Higor95y** [TurboWarp/packager#767] opened 2023-10-02 22:43 UTC
Please, if you can bring turbo warp to android, I would love it, personally, people who use android should also be recognized as users... but in my humble opinion, bring it to android

**Comment by CST1229** [comment] 2023-10-03 04:32
https://turbowarp.org/ can already be installed as a PWA (if your browser supports them there should be an install button that pops up somewhere).

**Comment by memer3638** [comment] 2023-11-26 23:03
this is possible by naming it index.html then downloading a converter that converts it to a apk file but it would be better if you use this link which is a tutorial video https://www.youtube.com/watch?v=V57SYHLHWGo&t=118s

**Comment by PPPDUD** [comment] 2023-11-27 22:28
> this is possible by naming it index.html then downloading a converter that converts it to a apk file but it would be better if you use this link which is a tutorial video https://www.youtube.com/watch?v=V57SYHLHWGo&t=118s

That's for the Packager, and you can talk about that at #2.

**Comment by XZY123lol** [comment] 2023-12-20 19:20
> this is possible by naming it index.html then downloading a converter that converts it to a apk file but it would be better if you use this link which is a tutorial video https://www.youtube.com/watch?v=V57SYHLHWGo&t=118s

Nah it's better without website 2 apk builder There's only a fee, it's better to let turbowarp make a builder apk

**Comment by GarboMuffin** [comment] 2024-05-23 07:58
im going to close as a duplicate of #2

**Closed by GarboMuffin** 2024-05-23 07:58 UTC
