### ISSUE TITLE
Packager should be able to read the config json comment in the stage sprite

### ISSUE THREAD

**Issue by ffghdfh** [TurboWarp/packager#759] opened 2023-08-30 09:42 UTC
Honestly this is only a small inconvenience, but every time I hit package project and the packager hasn't been open for a while, I have to manually enter the fps, the stage size and so on and so forth, and I think it'd be really cool if it could automatically read the info from that json file that is saved as a comment to the stage, and set the settings accordingly.

**Comment by TheShovel** [comment] 2023-08-30 10:19
The packager removes all comments. They don't exist in the final file.
If you want, you can use the Runtime options extension and set all the values when the project starts.

**Comment by ffghdfh** [comment] 2023-08-30 11:00
But i'm not talking about the final file, i'm talking about how when you load in a .sb3 file, it should read that comment to fill out the runtime options part of the packager, aka this stuff
![image](https://github.com/TurboWarp/packager/assets/96344370/8b0bf83c-23fe-4be2-9269-b8aceef2c4ad)

**Comment by ffghdfh** [comment] 2023-08-30 11:08
that's peculiar, i just noticed that it said "this project has settings stored in it, which may override these settings." but then how come that when i usually load in a file, everything there is in it's default state?

**Comment by TheShovel** [comment] 2023-08-30 13:52
Ooh alright. The settings in the project file itself should actually change the values displayed in the packager instead of just saying that there are overrides. Not having it do that can be a little misleading.

**Comment by ffghdfh** [comment] 2023-09-02 18:51
> Ooh alright. The settings in the project file itself should actually change the values displayed in the packager instead of just saying that there are overrides. Not having it do that can be a little misleading.

Yep, (sorry for the late reply but) I completely agree! Or in the very least, disable any form of input for those fields.

**Comment by GarboMuffin** [comment] 2024-05-23 07:57
im going to close as a duplicate of #213

**Closed by GarboMuffin** 2024-05-23 07:57 UTC
