### ISSUE TITLE
Package to APK needs to be added

### ISSUE THREAD

**Issue by RealPeriwinkle** [TurboWarp/packager#721] opened 2023-07-19 22:35 UTC
I need packaging to apk so that anyone can use it to make mobile games and publish them on websites and appstores.

**Comment by Dhuls-Scratch** [comment] 2023-07-30 20:05
Duplicate of #2

**Comment by RealPeriwinkle** [comment] 2023-07-30 23:58
What does that mean?

**Comment by PPPDUD** [comment] 2024-05-12 23:28
Dupe of #2

**Comment by GarboMuffin** [comment] 2024-05-23 07:56
see above

**Closed by GarboMuffin** 2024-05-23 07:56 UTC
