### ISSUE TITLE
Not sure how to submit ideas, so I guess I'll just make an issue?

### ISSUE THREAD

**Issue by CatCentralGitHub** [TurboWarp/packager#618] opened 2023-01-01 01:36 UTC
It'd be cool to have a .apk export option, it's annoying to use a browser on my phone.

**Comment by lukas-studio-tv** [comment] 2023-01-01 21:24
Use Sketchware pro
Add your game's .html file to assets
Then add a WebView and load that asset
Simpliest, most customizable and fastest way to do this.
Probably the only free with no watermarks and ads.
I do not think the packager will ever have this as a feature, it's not so simple to just "generate an .apk file", and i think nearly impossible on the web.
Android uses Java, which is a compiled language totally different from JS, and the API is quite complex.
The only reason there are options for Electron is that those are prebuilt builds, the packager only adds the files. .apk files work a whole lot different, they need to be signed and you can't just "unzip" them to change an asset.
If it would be possible, then that'd be quite cool actually

**Comment by CST1229** [comment] 2023-01-01 21:46
#224

**Comment by CatCentralGitHub** [comment] 2023-01-02 18:50
> Use Sketchware pro Add your game's .html file to assets Then add a WebView and load that asset 
How do I do that? I can't figure that out...

**Comment by GarboMuffin** [comment] 2023-01-02 19:18
Closing this as a duplicate of https://github.com/TurboWarp/packager/issues/2

You can continue to discuss how to use sketchware pro here if you want

**Closed by GarboMuffin** 2023-01-02 19:18 UTC
