### ISSUE TITLE
Html Files Not Installing on Chromebook

### ISSUE THREAD

**Issue by Spew45** [TurboWarp/packager#383] opened 2022-05-10 20:26 UTC
I was trying to download a project on Chromebook, although it won't work and it does pop up the file and it doesn't download to the system. I tried using zip except I can't compile that all into one file.

**Comment by hello-smile6** [comment] 2022-05-10 20:29
> I was trying to download a project on Chromebook, although it won't work and it does pop up the file and it doesn't download to the system. I tried using zip except I can't compile that all into one file.

Did you open the .html file?

**Comment by GarboMuffin** [comment] 2022-05-11 00:54
There's something wrong with some Chromebooks that won't let them download HTML files and we don't know what...

duplicate of #357 

> > I was trying to download a project on Chromebook, although it won't work and it does pop up the file and it doesn't download to the system. I tried using zip except I can't compile that all into one file.
> 
> Did you open the .html file?

They can't open something they can't even download...

**Closed by GarboMuffin** 2022-05-11 00:54 UTC

**Comment by hello-smile6** [comment] 2022-05-11 22:32
You may be able to download it as a .txt, then rename it. That sometimes works for me.

**Comment by GarboMuffin** [comment] 2022-05-11 23:18
https://github.com/TurboWarp/packager/issues/357#issuecomment-1124376419
