### ISSUE TITLE
Chooseable Username

### ISSUE THREAD

**Issue by coconutk5335** [TurboWarp/packager#348] opened 2022-03-30 01:39 UTC
Players could insert their own names!!! A selectible thing for username input would be ; prompt user for username ; it could be the same color as varibles, accent, or preferably foreground. under it once you select the option there can be a check square to enable a name blocker thing so people dont be innapropiate or racist to go with average guidlines. (names should be allowed though)

**Comment by Dhuls-Scratch** [comment] 2022-04-01 12:30
Duplicate of #336

**Closed** 2022-04-01 15:53 UTC
Labels: duplicate
