### ISSUE TITLE
The sprite does not follow the mouse pointer correctly

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#494] opened 2022-08-05 17:17 UTC
I've created a custom icon sprite right inside TurboWarp for convenience. I assigned it the script `forever go to X (mouse pointer) and Y (mouse pointer)`.
I will attach below a video showing a test: https://youtu.be/O60JT92qbs8
This happens both in TurboWarp (online version) and in the file created by the online version of the packager in all environments.

**Comment by GarboMuffin** [comment] 2022-08-05 18:56
Is this a recent thing or has it always done that?

**Comment by Alestore** [comment] 2022-08-05 19:47
Always been like that.

**Comment by GarboMuffin** [comment] 2022-08-09 04:06
What's strange here is that it's clearly receiving mouse inputs because it can update the Y but it doesn't know the X changed. I'm inclined to blame this on Chromium or your browser. Does it work in another browser like Firefox and are you on a multi-monitor setup of some sort or is there anything else unusual about your setup?

**Comment by Alestore** [comment] 2022-08-09 06:48
I have not tested on other browsers, but I'm not on a multi-monitor setup.
Currently I'm on vacation so I'm using one monitor, mouse keyboard and audio jack 3,5 mm headset. That's all.
This evening I'll try on Firefox.
Also, this happens not only to me: I gave some Steam keys of my game to my friends and everyone had this problem.

**Comment by Alestore** [comment] 2022-10-04 12:20
Any update on that?

**Comment by GarboMuffin** [comment] 2022-10-04 15:20
I assume you've checked that this still happens in the latest update?

**Comment by Alestore** [comment] 2022-10-04 16:42
Yes

**Comment by GarboMuffin** [comment] 2022-10-05 03:47
Looks like we never quite ruled out the possibility of a bug in the project. Does this happen in https://scratch.mit.edu/projects/741149940/? If not could you record a video of your project with the target's x position, y position, and the player's direction visible?

**Comment by Alestore** [comment] 2022-10-05 12:52
It happens also with this project!

**Comment by Alestore** [comment] 2022-10-10 14:21
Here is the video for my project, but the same thing happens with the Scratch cat in the project you linked me, @GarboMuffin: https://youtu.be/O60JT92qbs8

**Comment by GarboMuffin** [comment] 2022-10-10 15:18
The unfortunate thing is that I can't reproduce this locally

**Comment by Alestore** [comment] 2022-10-10 15:32
Does that mean you don't have the problem like I do?

**Comment by Alestore** [comment] 2022-10-10 15:32
Does that mean you don't have the problem like I do?

**Comment by GarboMuffin** [comment] 2022-10-10 21:50
Correct

**Comment by Alestore** [comment] 2022-10-10 21:56
That's so strange. Like, everyone has this problem with my game and I have this issue also with the simple project you linked me. Tomorrow I will do a little test and I'll let you know here. Not sure but I think the issue could be my double monitor setup.

**Comment by Alestore** [comment] 2022-10-11 15:33
If it isn't too much, may I ask you to download my project either by packaging it yourself or by Steam (https://store.steampowered.com/app/2020850/Asteroid/)? You'll certainly notice the problem. Also my collaborator has this problem.

**Comment by GarboMuffin** [comment] 2022-10-17 01:29
Out of an abundance of caution I would rather not download and run random steam games for the time being

Could you record a short new video of https://scratch.mit.edu/projects/741149940/ with your system's mouse cursor visible in vanilla Scratch, TurboWarp, and the packager? Ideally without any custom JS or advanced settings. If possible see if it happens in Firefox instead of Chrome. I'm trying to see where the issue is. I still can't reproduce locally.

**Comment by Alestore** [comment] 2022-10-17 07:32
Ok I'll do it right now but keep in mind that I have this problem when I'm in full screen using a resolution of 640x360 for my project, because my monitor is 1920x1080 so I'll have to modify the resolution of the project you sent me for the problem to show.
Apparently, the problem is only seen when the cursor touches the edge of the packaged project in full screen with the full monitor resolution: like ALL the screen is covered by the project without any black border.

**Comment by Alestore** [comment] 2022-10-17 10:26
Here is the video: https://youtu.be/wYFqBjGNzqU

> Out of an abundance of caution I would rather not download and run random steam games for the time being
> 
> Could you record a short new video of https://scratch.mit.edu/projects/741149940/ with your system's mouse cursor visible in vanilla Scratch website, TurboWarp website, and the packaged project (can just cycle through them, ~10 seconds each)? Ideally without any custom JS or advanced settings. If possible see if it happens in Firefox instead of Chrome. I'm trying to see where the issue is. I still can't reproduce locally.

**Comment by GarboMuffin** [comment] 2022-10-17 14:21
I've been able to reproduce this now, thanks. Will look into it when I have more time.

**Comment by GarboMuffin** [comment] 2022-10-20 04:21
This is on the weekend to do list

**Comment by GarboMuffin** [comment] 2022-10-22 03:45
This should be fixed now

**Closed by GarboMuffin** 2022-10-22 03:45 UTC

**Comment by Alestore** [comment] 2022-10-22 06:21
It works for me! Thanks!
